export enum TokenType {
  Identifier = "Identifier",
  Number = "Number",
  String = "String",
  Template = "Template",
  RegExpLiteral = "RegExpLiteral",
  Punctuator = "Punctuator",
  Keyword = "Keyword",
  Comment = "Comment",
  EOF = "EOF",

  JSXText = "JSXText",
  JSXIdentifier = "JSXIdentifier",
  JSXTagStart = "JSXTagStart",
  JSXTagEnd = "JSXTagEnd",
  JSXSelfClosing = "JSXSelfClosing",
  JSXExpressionStart = "JSXExpressionStart",
  JSXExpressionEnd = "JSXExpressionEnd",
  JSXFragmentStart = "JSXFragmentStart",
  JSXFragmentEnd = "JSXFragmentEnd",
}

export const esKeywords = new Set([
  "fn",
  "return",
  "if",
  "else",
  "const",
  "var",
  "class",
  "extends",
  "import",
  "export",
  "from",
  "new",
])

export const punctuators = [
  "?.",
  "..",
  "...",
  "==",
  "!=",
  "<=",
  ">=",
  "=",
  "+",
  "-",
  "*",
  "/",
  "%",
  "<",
  ">",
  "(",
  ")",
  "{",
  "}",
  "[",
  "]",
  "|",
  ".",
  ";",
  ":",
  ",",
  "?",
].sort((a, b) => b.length - a.length)
